import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Layout from '../components/layout'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>UEBIT STRINGs</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Layout></Layout>

      
    </div>
  )
}
