import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Layout from '../components/layout'
import Script from 'next/script'


export default function Home() {
  return (
    <div className="overflow-y-scroll bg-darkblue text-white">
      <Head>
        <title>STr3292 | UEBIT STRINGs</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Script type="text/javascript" src="../scripts/plugins/vivus.min.js" />
      <Script type="text/javascript" src="../scripts/main.js" />

      <Layout />

      <div className="overflow-y-scroll bg-darkblue text-white">
        <header className="fixed w-full h-11 py-3 bg-nand-default">
          <div className="mx-auto max-w-screen-md">
            <h1 id="uebitLogo">
              <a href="./index.js">
                <svg id="uebitLogoLine" width="100%" height="100%" viewBox="0 0 1967 492" version="1.1"
                  className="h-5 w-20 mx-4 fill-white">
                  <path id="U2l" d="M309.359,482.817l-45.048,0l236.385,-474.114l90.096,-0" />
                  <path id="U2r" d="M309.359,482.817l45.048,0l236.385,-474.114l-90.096,-0" />
                  <path id="U1r" d="M281.999,402.187l-117.114,0l-39.006,-62.91l164.819,-330.574l-90.096,-0" />
                  <path id="U1l" d="M281.999,402.187l-40.2,80.63l-117.017,0l-88.999,-143.54l164.819,-330.574" />
                  <path id="E1t" d="M573.103,89.333l40.201,-80.63l277.582,-0" />
                  <path id="E1b" d="M573.103,89.333l277.582,-0l40.201,-80.63" />
                  <path id="E2t" d="M480.033,276.002l40.201,-80.63l277.582,-0" />
                  <path id="E2b" d="M480.033,276.002l277.582,-0l40.201,-80.63" />
                  <path id="E3t" d="M376.919,482.817l40.2,-80.63l277.582,0" />
                  <path id="E3b" d="M376.919,482.817l277.582,0l40.2,-80.63" />
                  <path id="B1t" d="M690.933,482.817l236.385,-474.114l390.189,-0" />
                  <path id="B1b"
                    d="M690.933,482.817l90.096,0l103.114,-206.815l187.486,-0l40.201,-80.63l-187.486,-0l52.869,-106.039l300.094,-0l40.2,-80.63" />
                  <path id="B2t" d="M803.541,482.817l40.2,-80.63l187.486,0l145.939,-292.708l90.096,0" />
                  <path id="B2b" d="M803.541,482.817l277.582,0l186.139,-373.338" />
                  <path id="It" d="M1103.63,482.817l40.2,-80.63l43.631,0l196.184,-393.484l133.727,-0" />
                  <path id="Ib" d="M1103.63,482.817l133.726,0l196.184,-393.484l43.631,-0l40.201,-80.63" />
                  <path id="Tt" d="M1499.91,89.333l40.201,-80.63l390.19,-0" />
                  <path id="Tb"
                    d="M1499.91,89.333l150.047,-0l-196.184,393.484l90.096,0l196.184,-393.484l150.047,-0l40.201,-80.63" />
                </svg>
                <svg id="uebitLogoFace" width="100%" height="100%" viewBox="0 0 1967 492" version="1.1"
                  className="h-5 w-20 mx-4 fill-white">
                  <path id="U2" d="M590.792,8.703l-90.096,-0l-236.385,474.114l90.096,0l236.385,-474.114Z" />
                  <path id="U1"
                    d="M200.602,8.703l-164.819,330.574l88.999,143.54l117.017,0l40.2,-80.63l-117.114,0l-39.006,-62.91l164.819,-330.574l-90.096,-0Z" />
                  <path id="E1" d="M613.304,8.703l-40.201,80.63l277.582,-0l40.201,-80.63l-277.582,-0Z" />
                  <path id="E2" d="M520.234,195.372l-40.201,80.63l277.582,-0l40.201,-80.63l-277.582,-0Z" />
                  <path id="E3" d="M417.119,402.187l-40.2,80.63l277.582,0l40.2,-80.63l-277.582,0Z" />
                  <path id="B2"
                    d="M803.541,482.817l277.582,0l186.139,-373.338l-90.096,0l-145.939,292.708l-187.486,0l-40.2,80.63Z" />
                  <path id="B1"
                    d="M690.933,482.817l90.096,0l103.114,-206.815l187.486,-0l40.201,-80.63l-187.486,-0l52.869,-106.039l300.094,-0l40.2,-80.63l-390.189,-0l-236.385,474.114Z" />
                  <path id="I"
                    d="M1143.84,402.187l-40.2,80.63l133.726,0l196.184,-393.484l43.631,-0l40.201,-80.63l-133.727,-0l-196.184,393.484l-43.631,0Z" />
                  <path id="T"
                    d="M1540.11,8.703l-40.201,80.63l150.047,-0l-196.184,393.484l90.096,0l196.184,-393.484l150.047,-0l40.201,-80.63l-390.19,-0Z" />
                </svg>
              </a>
            </h1>
          </div>
        </header>

        <main className="mx-auto max-w-screen-md pt-11 text-base">
          <article className="pt-4 pb-8">
            <h1 className="text-xl font-bold">
              ようこそ、
              <span className="italic">
                UEBIT STRING
              </span>
              へ
            </h1>
            <p className="text-gray">
              訪れてくれてサンキュ
            </p>
            <section id="social" className="py-4 mt-2">
              <h1 className="text-xl font-bold">
                STr3292
              </h1>
              <p className="text-gray">
                これが私
              </p>
              <ul className="mt-2 space-y-1 text-nand-lighter">
                <li>
                  <a href="https://twitter.com/STr3292" className="underline">
                    Twitter
                  </a>
                </li>
                <li>
                  <a href="https://www.instagram.com/str3292u/" className="underline">
                    Instagram
                  </a>
                </li>
                <li>
                  <a href="https://steamcommunity.com/id/str3292/" className="underline">
                    Steam
                  </a>
                </li>
                <li>
                  <a href="https://www.youtube.com/channel/UCKpHbYt5VuQZ6ePTgjVvhfQ" className="underline">
                    YouTube
                  </a>
                </li>
                <li>
                  <a href="https://soundcloud.com/6esqihtayvem" className="underline">
                    SoundCloud
                  </a>
                </li>
                <li>
                  <a href="https://scrapbox.io/uebit/" className="underline">
                    UEBIT ARCHIVEs
                  </a>
                  <span className="text-sm text-nand-dark">
                    (現在非公開)
                  </span>
                </li>
              </ul>
            </section>
            <section></section>
          </article>
        </main>
        <footer className="mx-auto max-w-screen-md text-right py-8">
          <p className="text-gray">
            ©︎ 2022 STr3292
          </p>
        </footer>

      </div>

    </div>
  )
}
